apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloappserver-deployment
  labels:
    app: helloappserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloappserver
  template:
    metadata:
      labels:
        app: helloappserver
    spec:
      containers:
      - name: hello
        image: damore82/hello:0.0.7-SNAPSHOT
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: "kubernetes"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: helloappserver
spec:
  selector:
    app: helloappserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080